<?php

namespace SilverStripe\ORM\Tests;

use Doctrine\DBAL\Schema\Schema;
use SilverStripe\ORM\Connect\MySQLSchemaManager;
use SilverStripe\ORM\DB;
use SilverStripe\ORM\FieldType\DBClassName;
use SilverStripe\ORM\DataObject;
use SilverStripe\Dev\SapphireTest;
use SilverStripe\ORM\Tests\DataObjectSchemaGenerationTest\TestIndexObject;
use SilverStripe\ORM\Tests\DataObjectSchemaGenerationTest\TestObject;

class DataObjectSchemaGenerationTest extends SapphireTest
{

    protected static $extra_dataobjects = array(
        TestObject::class,
        TestIndexObject::class
    );

    public static function setUpBeforeClass()
    {

        // @todo - This test needs re-architecting because DB schema builds are generated by comparing
        // the current schema vs a blank schema which is completely re-built using all objects. We can't
        // just re-add a single object in isolation, we have to add all objects that make the current schema

        // enable fulltext option on this table
        TestIndexObject::config()->update(
            'create_table_options',
            array(MySQLSchemaManager::ID => 'ENGINE=MyISAM')
        );

        parent::setUpBeforeClass();
    }

    public function tearDown()
    {
        if (in_array('DataOBJECTSchemaGenerationTest_do', DB::table_list())) {
            // @todo - remove this - reset the DB table name as the case fixing test is failing at the moment
            DB::get_schema()->renameTable(
                'DataOBJECTSchemaGenerationTest_do',
                '__TEMP__DataOBJECTSchemaGenerationTest_do'
            );
            DB::get_schema()->renameTable(
                '__TEMP__DataOBJECTSchemaGenerationTest_do',
                'DataObjectSchemaGenerationTest_DO'
            );
        }

        parent::tearDown();
    }

    /**
     * @skipUpgrade
     */
    public function testTableCaseFixed()
    {

        // @todo - this test is not working because DBAL does a case-insensitive comparison of table names
        // need to get in touch with doctrine about how to best solve this problem

        // Modify table case
        DB::get_schema()->renameTable(
            'DataObjectSchemaGenerationTest_DO',
            '__TEMP__DataOBJECTSchemaGenerationTest_do'
        );
        DB::get_schema()->renameTable(
            '__TEMP__DataOBJECTSchemaGenerationTest_do',
            'DataOBJECTSchemaGenerationTest_do'
        );

        // Check table
        $tables = DB::table_list();
        $this->assertEquals(
            'DataOBJECTSchemaGenerationTest_do',
            $tables['dataobjectschemagenerationtest_do']
        );

        // Rebuild table
        $schema = DB::get_schema()->createSchema();
        $newSchema = clone $schema;
        $newSchema->dropTable('DataObjectSchemaGenerationTest_DO');
        TestObject::singleton()->augmentDBSchema($newSchema);
        $migrateSQL = $schema->getMigrateToSql($newSchema, DB::get_conn()->getDatabasePlatform());

        foreach ($migrateSQL as $query) {
            DB::get_conn()->exec($query);
        }

        // Check table
        $tables = DB::table_list();
        $this->assertEquals(
            'DataObjectSchemaGenerationTest_DO',
            $tables['dataobjectschemagenerationtest_do']
        );
    }

    /**
     * Check that once a schema has been generated, then it doesn't need any more updating
     */
    public function testFieldsDontRerequestChanges()
    {
        $schema = DB::get_schema()->createSchema();
        $newSchema = clone $schema;
        $newSchema->dropTable('DataObjectSchemaGenerationTest_DO');

        // Table will have been initially created by the $extraDataObjects setting

        // Verify that it doesn't need to be recreated
        TestObject::singleton()->augmentDBSchema($newSchema);

        $migrateSQL = $schema->getMigrateToSql($newSchema, DB::get_conn()->getDatabasePlatform());

        $this->assertEmpty($migrateSQL);
    }

    /**
     * Check that updates to a class fields are reflected in the database
     */
    public function testFieldsRequestChanges()
    {
        $schema = DB::get_schema()->createSchema();
        $newSchema = clone $schema;
        $newSchema->dropTable('DataObjectSchemaGenerationTest_DO');

        // Table will have been initially created by the $extraDataObjects setting

        // Let's insert a new field here
        TestObject::config()->update(
            'db',
            array(
                'SecretField' => 'Varchar(100)'
            )
        );

        // Verify that the above extra field triggered a schema update

        TestObject::singleton()->augmentDBSchema($newSchema);

        $migrateSQL = $schema->getMigrateToSql($newSchema, DB::get_conn()->getDatabasePlatform());

        $this->assertNotEmpty($migrateSQL);
    }

    /**
     * Check that indexes on a newly generated class do not subsequently request modification
     */
    public function testIndexesDontRerequestChanges()
    {
        $schema = DB::get_schema()->createSchema();
        $newSchema = clone $schema;
        $newSchema->dropTable('DataObjectSchemaGenerationTest_IndexDO');

        // Table will have been initially created by the $extraDataObjects setting

        // Verify that it doesn't need to be recreated
        TestIndexObject::singleton()->augmentDBSchema($newSchema);

        $migrateSQL = $schema->getMigrateToSql($newSchema, DB::get_conn()->getDatabasePlatform());

        $this->assertEmpty($migrateSQL);

        // Test with alternate index format, although these indexes are the same
        $config = TestIndexObject::config();
        $config->set('indexes', $config->get('indexes_alt'));

        $newSchema->dropTable('DataObjectSchemaGenerationTest_IndexDO');
        TestIndexObject::singleton()->augmentDBSchema($newSchema);

        // Verify that it still doesn't need to be recreated

        $migrateSQL = $schema->getMigrateToSql($newSchema, DB::get_conn()->getDatabasePlatform());

        $this->assertEmpty($migrateSQL);
    }

    /**
     * Check that updates to a dataobject's indexes are reflected in DDL
     */
    public function testIndexesRerequestChanges()
    {
        $schema = DB::get_schema()->createSchema();
        $newSchema = clone $schema;
        $newSchema->dropTable('DataObjectSchemaGenerationTest_IndexDO');

        // Table will have been initially created by the $extraDataObjects setting

        // Update the SearchFields index here
        TestIndexObject::config()->update(
            'indexes',
            [
                'SearchFields' => [
                    'columns' => ['Title'],
                ],
            ]
        );

        // Verify that the above index change triggered a schema update
        TestIndexObject::singleton()->augmentDBSchema($newSchema);

        $migrateSQL = $schema->getMigrateToSql($newSchema, DB::get_conn()->getDatabasePlatform());

        $this->assertNotEmpty($migrateSQL);
    }

    /**
     * Tests the generation of the ClassName spec and ensure it's not unnecessarily influenced
     * by the order of classnames of existing records
     */
    public function testClassNameSpecGeneration()
    {
        $schema = DataObject::getSchema();

        // Test with blank entries
        DBClassName::clear_classname_cache();
        $do1 = new TestObject();
        $fields = $schema->databaseFields(TestObject::class, false);
        /**
 * @skipUpgrade
*/
        $this->assertEquals("DBClassName", $fields['ClassName']);
        $this->assertEquals(
            array(
                TestObject::class => TestObject::class,
                TestIndexObject::class => TestIndexObject::class
            ),
            $do1->dbObject('ClassName')->getEnum()
        );


        // Test with instance of subclass
        $item1 = new TestIndexObject();
        $item1->write();
        DBClassName::clear_classname_cache();
        $this->assertEquals(
            array(
                TestObject::class => TestObject::class,
                TestIndexObject::class => TestIndexObject::class
            ),
            $item1->dbObject('ClassName')->getEnum()
        );
        $item1->delete();

        // Test with instance of main class
        $item2 = new TestObject();
        $item2->write();
        DBClassName::clear_classname_cache();
        $this->assertEquals(
            array(
                TestObject::class => TestObject::class,
                TestIndexObject::class => TestIndexObject::class
            ),
            $item2->dbObject('ClassName')->getEnum()
        );
        $item2->delete();

        // Test with instances of both classes
        $item1 = new TestIndexObject();
        $item1->write();
        $item2 = new TestObject();
        $item2->write();
        DBClassName::clear_classname_cache();
        $this->assertEquals(
            array(
                TestObject::class => TestObject::class,
                TestIndexObject::class => TestIndexObject::class
            ),
            $item1->dbObject('ClassName')->getEnum()
        );
        $item1->delete();
        $item2->delete();
    }
}
